name: Auth Service CI/CD

on:
  push:
    branches: [ "main" ]
    # 1. ONLY trigger if changes happen in the auth service folder
    paths:
      - 'backend/user-auth-service/**' 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        # 2. Add the folder path to the end of the build command
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/book-corner-auth-service:latest ./backend/user-auth-service

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/book-corner-auth-service:latest
